version: '3.8'

services:

  api:
    container_name: truthy-vs-falsy_api
    image: rahmi-tufanoglu/truthy-vs-falsy-api
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgres://postgres:${DATABASE_PASSWORD}@postgres:${DATABASE_PORT}/${DATABASE_NAME}"
      NODE_ENV: development
      PORT: 3000
    ports:
      - 8080:3000

  db:
    container_name: postgres_db
    image: postgres:13.2-alpine
    restart: always
    environment:
      POSTGRES_USER: "${DATABASE_USERNAME}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_DATABASE: "${DATABASE_DATABASE}"
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql
